### ISSUE TITLE
Failed to start Vite dev server

### ISSUE THREAD

**Issue by NexZhu** [webfansplz/vite-plugin-vue-inspector#28]
Error log:
```
failed to load config from /root/dev/web/daotl-vitesse/vite.config.ts
error when starting dev server:
file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite-plugin-vue-inspector@1.1.3_vite@3.2.2/node_modules/vite-plugin-vue-inspector/dist/index.mjs:32
import { parse as babelParse, traverse as babelTraverse } from "@babel/core";
                              ^^^^^^^^
SyntaxError: Named export 'traverse' not found. The requested module '@babel/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@babel/core';
const { parse: babelParse, traverse: babelTraverse } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async loadConfigFromBundledFile (file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:64010:21)
    at async loadConfigFromFile (file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:63895:28)
    at async resolveConfig (file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:63519:28)
    at async createServer (file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:62819:20)
    at async CAC.<anonymous> (file:///root/dev/web/daotl-vitesse/node_modules/.pnpm/vite@3.2.2/node_modules/vite/dist/node/cli.js:707:24)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by webfansplz** [comment]
Can you provide a mini repo?

**Comment by NexZhu** [comment]
@webfansplz Uncomment `// Inspector()` in https://github.com/daotl/vitesse/blob/main/vite.config.ts and you can reproduce the error.
